
/*
 * Copyright (C) 1985-1992  New York University
 * 
 * This file is part of the Ada/Ed-C system.  See the Ada/Ed README file for
 * warranty (none) and distribution info and also the GNU General Public
 * License for more details.

 */

/* Node kind definitions */
#define NUM_NODES 145

#define AS_PRAGMA 0
#define AS_ARG 1
#define AS_OBJ_DECL 2
#define AS_CONST_DECL 3
#define AS_NUM_DECL 4
#define AS_TYPE_DECL 5
#define AS_SUBTYPE_DECL 6
#define AS_SUBTYPE_INDIC 7
#define AS_DERIVED_TYPE 8
#define AS_RANGE 9
#define AS_RANGE_ATTRIBUTE 10
#define AS_CONSTRAINT 11
#define AS_ENUM 12
#define AS_INT_TYPE 13
#define AS_FLOAT_TYPE 14
#define AS_FIXED_TYPE 15
#define AS_DIGITS 16
#define AS_DELTA 17
#define AS_ARRAY_TYPE 18
#define AS_BOX 19
#define AS_SUBTYPE 20
#define AS_RECORD 21
#define AS_COMPONENT_LIST 22
#define AS_FIELD 23
#define AS_DISCR_SPEC 24
#define AS_VARIANT_DECL 25
#define AS_VARIANT_CHOICES 26
#define AS_STRING 27
#define AS_SIMPLE_CHOICE 28
#define AS_RANGE_CHOICE 29
#define AS_CHOICE_UNRESOLVED 30
#define AS_OTHERS_CHOICE 31
#define AS_ACCESS_TYPE 32
#define AS_INCOMPLETE_DECL 33
#define AS_DECLARATIONS 34
#define AS_LABELS 35
#define AS_CHARACTER_LITERAL 36
#define AS_SIMPLE_NAME 37
#define AS_CALL_UNRESOLVED 38
#define AS_SELECTOR 39
#define AS_ALL 40
#define AS_ATTRIBUTE 41
#define AS_AGGREGATE 42
#define AS_PARENTHESIS 43
#define AS_CHOICE_LIST 44
#define AS_OP 45
#define AS_IN 46
#define AS_NOTIN 47
#define AS_UN_OP 48
#define AS_INT_LITERAL 49
#define AS_REAL_LITERAL 50
#define AS_STRING_LITERAL 51
#define AS_NULL 52
#define AS_NAME 53
#define AS_QUALIFY 54
#define AS_NEW_INIT 55
#define AS_NEW 56
#define AS_STATEMENTS 57
#define AS_STATEMENT 58
#define AS_NULL_S 59
#define AS_ASSIGNMENT 60
#define AS_IF 61
#define AS_COND_STATEMENTS 62
#define AS_CONDITION 63
#define AS_CASE 64
#define AS_CASE_STATEMENTS 65
#define AS_LOOP 66
#define AS_WHILE 67
#define AS_FOR 68
#define AS_FORREV 69
#define AS_BLOCK 70
#define AS_EXIT 71
#define AS_RETURN 72
#define AS_GOTO 73
#define AS_SUBPROGRAM_DECL 74
#define AS_PROCEDURE 75
#define AS_FUNCTION 76
#define AS_OPERATOR 77
#define AS_FORMAL 78
#define AS_MODE 79
#define AS_SUBPROGRAM 80
#define AS_CALL 81
#define AS_PACKAGE_SPEC 82
#define AS_PACKAGE_BODY 83
#define AS_PRIVATE_DECL 84
#define AS_USE 85
#define AS_RENAME_OBJ 86
#define AS_RENAME_EX 87
#define AS_RENAME_PACK 88
#define AS_RENAME_SUB 89
#define AS_TASK_SPEC 90
#define AS_TASK_TYPE_SPEC 91
#define AS_TASK 92
#define AS_ENTRY 93
#define AS_ENTRY_FAMILY 94
#define AS_ACCEPT 95
#define AS_DELAY 96
#define AS_SELECTIVE_WAIT 97
#define AS_GUARD 98
#define AS_ACCEPT_ALT 99
#define AS_DELAY_ALT 100
#define AS_TERMINATE_ALT 101
#define AS_CONDITIONAL_ENTRY_CALL 102
#define AS_TIMED_ENTRY_CALL 103
#define AS_ABORT 104
#define AS_UNIT 105
#define AS_WITH_USE_LIST 106
#define AS_WITH 107
#define AS_SUBPROGRAM_STUB 108
#define AS_PACKAGE_STUB 109
#define AS_TASK_STUB 110
#define AS_SEPARATE 111
#define AS_EXCEPTION 112
#define AS_EXCEPT_DECL 113
#define AS_HANDLER 114
#define AS_OTHERS 115
#define AS_RAISE 116
#define AS_GENERIC_FUNCTION 117
#define AS_GENERIC_PROCEDURE 118
#define AS_GENERIC_PACKAGE 119
#define AS_GENERIC_FORMALS 120
#define AS_GENERIC_OBJ 121
#define AS_GENERIC_TYPE 122
#define AS_GEN_PRIV_TYPE 123
#define AS_GENERIC_SUBP 124
#define AS_GENERIC 125
#define AS_PACKAGE_INSTANCE 126
#define AS_FUNCTION_INSTANCE 127
#define AS_PROCEDURE_INSTANCE 128
#define AS_INSTANCE 129
#define AS_LENGTH_CLAUSE 130
#define AS_ENUM_REP_CLAUSE 131
#define AS_REC_REP_CLAUSE 132
#define AS_COMPON_CLAUSE 133
#define AS_ADDRESS_CLAUSE 134
#define AS_ANY_OP 135
#define AS_OPT 136
#define AS_LIST 137
#define AS_RANGE_EXPRESSION 138
#define AS_ARG_ASSOC_LIST 139
#define AS_PRIVATE 140
#define AS_LIMITED_PRIVATE 141
#define AS_CODE 142
#define AS_LINE_NO 143
#define AS_FREE 144
