
/* Token Codes for Reserved Words */

#define XABORT                300
#define XABS                  301
#define XACCEPT               302
#define XACCESS               303
#define XALL                  304
#define XAND                  305
#define XARRAY                306
#define XAT                   307
#define XBEGIN                308
#define XBODY                 309
#define XCASE                 310
#define XCONSTANT             311
#define XDECLARE              312
#define XDELAY                313
#define XDELTA                314
#define XDIGITS               315
#define XDO                   316
#define XELSE                 317
#define XELSIF                318
#define XEND                  319
#define XENTRY                320
#define XEXCEPTION            321
#define XEXIT                 322
#define XFOR                  323
#define XFUNCTION             324
#define XGENERIC              325
#define XGOTO                 326
#define XIF                   327
#define XIN                   328
#define XIS                   329
#define XLIMITED              330
#define XLOOP                 331
#define XMOD                  332
#define XNEW                  333
#define XNOT                  334
#define XNULL                 335
#define XOF                   336
#define XOR                   337
#define XOTHERS               338
#define XOUT                  339
#define XPACKAGE              340
#define XPRAGMA               341
#define XPRIVATE              342
#define XPROCEDURE            343
#define XRAISE                344
#define XRANGE                345
#define XRECORD               346
#define XREM                  347
#define XRENAMES              348
#define XRETURN               349
#define XREVERSE              350
#define XSELECT               351
#define XSEPARATE             352
#define XSUBTYPE              353
#define XTASK                 354
#define XTERMINATE            355
#define XTHEN                 356
#define XTYPE                 357
#define XUSE                  358
#define XWHEN                 359
#define XWHILE                360
#define XWITH                 361
#define XXOR                  362

#define NO_KEYWORDS            63



/* Token Codes for Attributes */

#define XA_ADDRESS              400
#define XA_AFT                  401
#define XA_BASE                 402
#define XA_CALLABLE             403
#define XA_CONSTRAINED          404
#define XA_COUNT                405
#define XA_DELTA                406
#define XA_DIGITS               407
#define XA_EMAX                 408
#define XA_EPSILON              409
#define XA_FIRST                410
#define XA_FIRST_BIT            411
#define XA_FORE                 412
#define XA_IMAGE                413
#define XA_LARGE                414
#define XA_LAST                 415
#define XA_LENGTH               416
#define XA_MACHINE_EMAX         417
#define XA_MACHINE_EMIN         418
#define XA_MACHINE_MANTISSA     419
#define XA_MACHINE_OVERFLOWS    420
#define XA_MACHINE_RADIX        421
#define XA_MACHINE_ROUNDS       422
#define XA_MANTISSA             423
#define XA_POS                  424
#define XA_POSITION             425
#define XA_PRED                 426
#define XA_RANGE                427
#define XA_SAFE_EMAX            428
#define XA_SAFE_LARGE           429
#define XA_SAFE_SMALL           430
#define XA_SIZE                 431
#define XA_SMALL                432
#define XA_STORAGE_SIZE         433
#define XA_SUCC                 434
#define XA_TERMINATED           435
#define XA_VAL                  436
#define XA_VALUE                437
#define XA_WIDTH                438
#define XA_LAST_BIT             439

#define NO_ATTS                  40

/* Other tokens */

#define XID                     500
#define XSTRLIT                 501
#define XREALLIT                502
#define XINTEGERLIT             503
#define XDOTDOT                 504
#define XCHARLIT                505
#define XATTMARK                506
#define XASSIGN                 507
#define XARIT                   508
#define XMULT                   509
#define XEXP                    510
#define XREL                    511
#define XLOG                    512
#define XLTGT                   513
#define XEQGT                   514


